# Generated by Django 5.2.3 on 2025-06-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NV',
            fields=[
                ('ma_nv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('cong_ty', models.CharField(max_length=100)),
                ('phong_ban', models.CharField(max_length=100)),
                ('chuc_vu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TS',
            fields=[
                ('ma_ts', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_ts', models.CharField(max_length=200)),
                ('loai_ts', models.CharField(max_length=100)),
                ('don_vi', models.CharField(max_length=50)),
                ('tinh_trang', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BG',
            fields=[
                ('ma_bg', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_giao', models.DateField()),
                ('ghi_chu', models.TextField(blank=True)),
                ('nguoi_giao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_giao', to='inventory.nv')),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_nhan', to='inventory.nv')),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ts')),
            ],
        ),
    ]
