# Generated by Django 5.2.1 on 2025-06-16 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ts',
            name='khau_hao_nam',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ts',
            name='ngay_mua',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
